name: Run isort

on:
  - fork
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.3
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "pyproject.toml"
            version: "~=5.12.0"